CREATE TABLE [dbo].[HOA_DON_BAN_HANG]
(
[ID] [int] NOT NULL,
[IDCashier] [int] NOT NULL,
[ThoiGian] [date] NOT NULL,
[TongTien] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HOA_DON_BAN_HANG] ADD CONSTRAINT [PK__HOA_DON___3214EC27D60FC6F4] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HOA_DON_BAN_HANG] ADD CONSTRAINT [fk_CS] FOREIGN KEY ([IDCashier]) REFERENCES [dbo].[CASHIER] ([ID])
GO
ALTER TABLE [dbo].[HOA_DON_BAN_HANG] ADD CONSTRAINT [fk_HD] FOREIGN KEY ([ID]) REFERENCES [dbo].[HOA_DON_CHI_TIET] ([ID])
GO
