CREATE TABLE [dbo].[NHA_SAN_XUAT]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[TenNhaSX] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NHA_SAN_XUAT] ADD CONSTRAINT [PK__NHA_SAN___3214EC27DB0D57AF] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
