CREATE TABLE [dbo].[HOA_DON_CHI_TIET]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[IDHang] [int] NOT NULL,
[SoLuong] [int] NOT NULL,
[DonGia] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[GiamGia] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ThanhTien] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HOA_DON_CHI_TIET] ADD CONSTRAINT [PK__HOA_DON___3214EC27DE5FB5C5] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HOA_DON_CHI_TIET] ADD CONSTRAINT [fk_hanghoa] FOREIGN KEY ([IDHang]) REFERENCES [dbo].[HANG] ([ID])
GO
