CREATE TABLE [dbo].[ACCOUNT]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[UserName] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PW] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Loai] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACCOUNT] ADD CONSTRAINT [PK__ACCOUNT__3214EC27C6E150BA] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
