CREATE TABLE [dbo].[HANG]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[TenMatHang] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IDLoaiHang] [int] NOT NULL,
[IDNhaSX] [int] NOT NULL,
[IDMaGG] [int] NULL,
[Gia] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[HSD] [date] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HANG] ADD CONSTRAINT [PK__HANG__3214EC27E49D774D] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HANG] ADD CONSTRAINT [fk_hangupdate] FOREIGN KEY ([IDLoaiHang]) REFERENCES [dbo].[LOAI_HANG] ([ID])
GO
ALTER TABLE [dbo].[HANG] ADD CONSTRAINT [fk_mgg] FOREIGN KEY ([IDMaGG]) REFERENCES [dbo].[MA_GIAM_GIA] ([ID])
GO
ALTER TABLE [dbo].[HANG] ADD CONSTRAINT [fk_nhasx] FOREIGN KEY ([IDNhaSX]) REFERENCES [dbo].[NHA_SAN_XUAT] ([ID])
GO
