CREATE TABLE [dbo].[MA_GIAM_GIA]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[DiscountPerPro] [float] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MA_GIAM_GIA] ADD CONSTRAINT [PK__MA_GIAM___3214EC270F4B1A5B] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
