CREATE TABLE [dbo].[LOAI_HANG]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[TenLoaiSH] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAI_HANG] ADD CONSTRAINT [PK__LOAI_HAN__3214EC274F326BE0] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
