CREATE TABLE [dbo].[CASHIER]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[HoVaTen] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[GioiTinh] [int] NOT NULL,
[SDT] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DiaChi] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IDAccount] [int] NOT NULL,
[IDShift] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CASHIER] ADD CONSTRAINT [PK__CASHIER__3214EC27E810A04E] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CASHIER] ADD CONSTRAINT [fk_account] FOREIGN KEY ([IDAccount]) REFERENCES [dbo].[ACCOUNT] ([ID])
GO
ALTER TABLE [dbo].[CASHIER] ADD CONSTRAINT [fk_shift] FOREIGN KEY ([IDShift]) REFERENCES [dbo].[CA_LAM_VIEC] ([ID])
GO
