CREATE TABLE [dbo].[CA_LAM_VIEC]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[ThoiGianLamViec] [date] NOT NULL,
[ThongBao] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CA_LAM_VIEC] ADD CONSTRAINT [PK__CA_LAM_V__3214EC271FACFC89] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
